In [ ]:
import numpy as np
# задание 1
arr1 = np.array([[1, 2, 1], [-2, 1, 1]])
arr2 = np.array([[3, 1], [-1, 0], [2, 4]])
arr3 = np.array([[-2, 2], [1, -1], [1, 2]])
a = np.transpose(arr1)
u1=a+2*arr2
u2=arr2+arr3*2
print(u1)
print(u2)


[[7 0]
 [0 1]
 [5 9]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [ ]:
import numpy as np
# задание 2
arr4 = np.zeros((8, 8))
print(arr4)
arr4[::1,1::2]= 1
print(arr4)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [2]:
import numpy as np
# задание 3
d1 = np.arange(start=0, stop=1.5, step=0.1)
print(d1)
d2 = np.arange(start=0, stop=6, step=1)
print(d2)
p2=d2.reshape((3, 2))
print(p2)
p1=d1.reshape((5, 3))
print(p1)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
